[package]
name = "dns"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
bitfield = "0.15.0"
hmac = "0.12.1"
p256 = "0.13.2"
rand = "0.8.5"
sha2 = "0.10.8"
x25519-dalek = "2.0.1"

[patch.crates-io]
curve25519-dalek = { path = "./curve25519-dalek/curve25519-dalek" }